name: GitHub Actions Discord Webhook
description: Sends the build status to a Discord webhook
branding:
  icon: bell
  color: gray-dark
inputs:
  webhook_url:
    description: The Discord webhook url
    required: true
  status:
    description: The build status
    required: false
    default: ${{ job.status }}
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/send.sh
      shell: bash
      env:
        WEBHOOK_URL: ${{ https://discord.com/api/webhooks/1289339182598324244/fnIyBuM5VjgexcboIxXBgCMQeNga0KVqhRppB-6K0beQf0LvWYmFzT9vHPMWH-TNWaxY }}
        BUILD_STATUS: ${{ inputs.status }}
